### ISSUE TITLE
decomposeParWing: Interpretation of Output unclear

### ISSUE THREAD

**Issue by mrwunderbar666** [kartiklakhotia/RECEIPT#1]
Hi,

thanks for sharing this interesting repository. I was experimenting with `decomposeParWing` but I am not sure what to make of the output.

Using the provided example dataset, I run the following command:

```bash
numactl -l ./decomposeParWing -i datasets/github.txt -o github_result.txt -t 8
```

And I get the following output:

```
12, 0, 934 
12, 2, 934 
12, 3, 816 
12, 4, 912 
12, 5, 934 
12, 6, 816 
12, 10, 816 
12, 11, 640 
14, 0, 1014 
14, 1, 1014 
...
177376, 15292, 0 
177377, 36949, 0 
177378, 94353, 0 
177379, 722, 0 
177380, 2513, 0 
177381, 668, 0 
177382, 44882, 0 
177383, 50589, 0 
177384, 887, 0 
177385, 52598, 0
```

There are two things that I do not understand, and maybe you could help me to clarify them.

First, the `v` values (or IDs) of the output start at 0, although the input data does not contain any zero IDs for `v`. Should I just add +1 to all of the `v` values?

Second, I noticed that the IDs of `u` in the input data only range until 56519. However, the output data goes to 177385. How to interpret these "new" IDs for `u`?

Thanks!

**Comment by kartiklakhotia** [comment]
Can you share your input dataset, a link to it or if it is small enough, via google drive or something?

**Comment by mrwunderbar666** [comment]
I was using the dataset that you provide in the repository: [github.txt](https://github.com/kartiklakhotia/RECEIPT/blob/master/datasets/github.txt). 

My personal dataset has the same issue, but is 44 MB, so a bit difficult to share

**Comment by kartiklakhotia** [comment]
Thank you for pointing this issue. The vertices were reordered for efficient butterfly counting and peeling. Unfortunately, I was using the reordered indices and not the original ones when printing the output. Have changed it now and it should print the output as expected.

**Comment by mrwunderbar666** [comment]
Beautiful, thanks! Can confirm that it works with the Github dataset. I also tried it with my own data and it seems to work. It is really a fast library, well done!

**Comment by kartiklakhotia** [comment]
Thank you!
